[package]
name = "fm_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
mysql = "26.0.1"
serde = { version = "1.0.228", features = ["derive"] } 
serde_json = "1.0.145"
sonyflake = "0.4.0"
tokio = { version = "1.47.1", features = ["full"] }
